server:
  port: 8083
  servlet:
    context-path: /post
  application:
    name: post-service

spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/post-service?authSource=admin
