server:
  port: 8081
  servlet:
    context-path: /profile
spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 12345678

kafka:
  bootstrap-servers: localhost:9094

management:
  tracing:
    sampling:
      probability: 1.0
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  endpoints:
    web.exposure:
      include: health, info, metrics, prometheus
  observations:
    key-values:
      application: profile-service
logging:
  pattern:
    correlation: '[${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
